loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
]

templates/parciais/_footer.html
{% load static %}
<footer class="footer_area clearfix" style="width: 1368px;">
    <div class="container">
        <div class="row align-items-center">
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-4">
                <div class="single_widget_area">
                    <!-- Logo -->
                    <div class="footer-logo mr-50">
                        <a href="index.html"><img src="{% static 'img/core-img/nova-logo2.jpg' %}" alt=""></a>
                    </div>
                    <!-- Copywrite Text -->
                    <p class="copywrite">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template
                        is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                            target="_blank">Colorlib</a> & Re-distributed by <a href="https://themewagon.com/"
                            target="_blank">Duduzinho</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-8">
                <div class="single_widget_area">
                    <!-- Footer Menu -->
                    <div class="footer_menu">
                        <nav class="navbar navbar-expand-lg justify-content-end">
                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false"
                                aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                            <div class="collapse navbar-collapse" id="footerNavContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="{% static 'index.html' %}">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% static 'shop.html' %}">Categorias</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% static 'product-details.html' %}">Produto</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% static 'cart.html' %}">Carrinho</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/active.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js'%}"></script>
<script src="{% static 'assets/custom/js/scripts.js'%}"></script>

templates/parciais/_head.html
{% load static %}

<meta charset="UTF-8">
<meta name="description" content="">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<!-- Title  -->
<title>{% block titulo %}EduStore{% endblock %}</title>

<!-- Favicon  -->
<link rel="icon" href="{% static 'img/core-img/iconnn.jpg' %}">

<!-- Core Style CSS -->
<link rel="stylesheet" href="{% static 'css/core-style.css' %}">
<link rel="stylesheet" href="{% static 'style.css' %}">

templates/parciais/_messages.html
{% if messages %}
<br>
{% for message in messages %}
<div class="container">
    <div id="laranja" class="alert {{ message.tags }}" role="alert">
        {{ message }}
    </div>
</div>
<style>
    #laranja {
        margin-top: 0;
    }
</style>
{% endfor %}
{% endif %}

templates/parciais/_nav.html
{% load static %}
{% load eofilters %}
<div class="search-wrapper section-padding-100">
    <div class="search-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="search-content">
                    <form action="#" method="get">
                        <input type="search" name="search" id="search" placeholder="Type your keyword...">
                        <button type="submit"><img src="{% static 'img/core-img/search.png' %}" alt=""></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="main-content-wrapper d-flex clearfix">

    <div class="mobile-nav">
        <div class="amado-navbar-brand">
            <a href=""><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
        </div>
        <div class="amado-navbar-toggler">
            <span></span><span></span><span></span>
        </div>
    </div>

    <header class="header-area clearfix" style="background: #252525;">
        <div class="nav-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="logo">
            <a href="/"><img src="{% static 'img/core-img/nova-logo.jpg' %}" alt=""></a>
        </div>
        <nav class="amado-nav">
            <ul>
                <li class="active"><a href="{% static 'index.html' %}" style="color:white;">Home</a></li>
                <li><a href="{% static 'shop.html' %}" style="color:white;">Categorias</a></li>
                <li><a href="{% static 'product-details.html' %}" style="color:white;">Produtos</a></li>
                <li><a href="{% url 'produto:carrinho' %}" style="color:white;">Carrinho</a></li>
            </ul>
        </nav>
        <div class="amado-btn-group mt-30 mb-100">
            <a href="#" class="btn amado-btn mb-15">Descontos</a>
            <a href="#" class="btn amado-btn active">Novidades</a>
        </div>
        <div class="cart-fav-search mb-100">
            <a href="cart.html" class="cart-nav" style="color:white;"><img src="{% static 'img/core-img/cart.png' %}"
                    alt=""> Carrinho</span></a>
            <a href="#" class="fav-nav" style="color:white;"><img src="{% static 'img/core-img/favorites.png' %}"
                    alt="">Favoritos</a>
            <a href="#" class="search-nav" style="color:white;"><img src="{% static 'img/core-img/search.png' %}"
                    alt="">Procurar</a>
        </div>
        <div class="social-info d-flex justify-content-between">
            <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
        </div>
    </header>
    <!-- Header Area End -->
    <script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js'%}"></script>
    <script src="{% static 'assets/bootstrap/js/popper.min.js'%}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
    <script defer src="{% static 'assets/font-awesome/js/all.js'%}"></script>
    <script src="{% static 'assets/custom/js/scripts.js'%}"></script>

templates/parciais/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %}

            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
            </li>
            {% endif %}
    </ul>
</div>
{% endif %}

templates/parciais/_script.html
{% load static %}
<!-- Popper js -->

<script src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap js -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Plugins js -->
<script src="{% static 'js/plugins.js' %}"></script>

templates/parciais/_test.html
{% load static %}

<script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
<!-- Popper js -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap js -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Plugins js -->
<script src="{% static 'js/plugins.js' %}"></script>
<!-- Active js -->