loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
]

produto/models.py
from ctypes import resize
from pickletools import optimize
from pyexpat import model
from tabnanny import verbose
from tkinter import CASCADE
from xml.etree.ElementInclude import default_loader
from django.db import models
from PIL import Image
from django.conf import settings
import os
from django.utils.text import slugify


class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    imagem = models.ImageField(upload_to='produto_imagens/%Y/%m', blank=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promocional = models.FloatField(
        default=0, verbose_name='Preço Promo.')
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variavel'),
            ('S', 'Simples'),
        )
    )

    def get_preco_formatado(self):
        return f'R$ {self.preco_marketing:.2f}'.replace('.', ',')
    get_preco_formatado.short_description = 'Preço'

    def get_preco_formatado_promocional(self):
        return f'R& {self.preco_marketing_promocional:.2f}'.replace('.', ',')
    get_preco_formatado_promocional.short_description = 'Preço Promo'

    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= 800:
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome


class Variacao(models.Model):
    nome = models.CharField(max_length=50, blank=True, null=True)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    class Meta:
        verbose_name = 'Váriavel'
        verbose_name_plural = 'Variações'

produto/views.py
from pprint import pprint
from email.mime import image
from django import views
from django import http
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from . import models


class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 10


class DetalheProduto(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'


class AdicionarAoCarrinho(View):
    def get(self, *args, **kwargs):
        # if self.request.session.get('carrinho'):
        #    del self.request.session['carrinho']
        #   self.request.session.save()
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            messages.error(
                self.request,
                'Produto não existe'
            )
            return redirect(http_referer)

        variacao = get_object_or_404(models.Variacao, id=variacao_id)
        produto = variacao.produto
        variacao_estoque = variacao.estoque
        produto_id = produto.id
        produto_nome = produto.nome
        variacao_nome = variacao.nome or ""
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem

        imagem = imagem.name

        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Produto Esgotado'
            )
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        carrinho = self.request.session['carrinho']

        if variacao_id in carrinho:
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            if variacao_estoque < quantidade_carrinho:
                messages.error(
                    self.request,
                    f'Estoque insuficiente para'
                    f' "{produto_nome}"! Adicionamos {variacao_estoque}x'
                    f' no seu carrinho'
                )
                quantidade_carrinho = variacao_estoque

            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * \
                quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * \
                quantidade_carrinho

        else:
            carrinho[variacao_id] = {
                'produto_id': produto_id,
                'produto_nome': produto_nome,
                'variacao_nome': variacao_nome,
                'variacao_id': variacao_id,
                'preco_unitario': preco_unitario,
                'preco_unitario_promocional': preco_unitario_promocional,
                'preco_quantitativo': preco_unitario,
                'preco_quantitativo_promocional': preco_unitario_promocional,
                'quantidade': 1,
                'slug': slug,
                'imagem': imagem,
            }

        self.request.session.save()

        messages.success(
            self.request,
            f'Produto {produto_nome} {variacao_nome} adicionado ao seu'
            f'carrinho {carrinho[variacao_id]["quantidade"]}x.'
        )

        return redirect(http_referer)


class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)

        carrinho = self.request.session['carrinho'][variacao_id]

        messages.success(
            self.request,
            f'Produto {carrinho["produto_nome"]} {carrinho["variacao_nome"]} '
            f'removido do seu carrinho'
        )

        del self.request.session['carrinho'][variacao_id]

        self.request.session.save()

        return redirect(http_referer)


class Carrinho(View):
    def get(self, *args, **kwargs):

        contexto = {
            'carrinho': self.request.session.get('carrinho', {})
        }

        return render(self.request, 'produto/carrinho.html', contexto)


class ResumoDaCompra(View):
    def get(*args, **kwargs):
        return HttpResponse('Finalizar ')

produto/templates/produto/carrinho.html
{% load static %}
{% load eofilters %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'parciais/_head.html' %}
</head>

<body style="background: #252525;">

    {% include 'parciais/_nav.html' %}
    {% if carrinho %}
    <div class="cart-table-area section-padding-100">
        <div class="container-fluid">
            {% include 'parciais/_messages.html' %}
            <div class="row">
                <div class="col-12 col-lg-8">


                    <div class="cart-table clearfix">
                        <table class="table table-responsive" id="tabelinha">
                            <div class="cart-title mt-50">
                                <h2 style="color: #fbb710">Carrinho</h2>
                            </div>
                            <thead>
                                <tr style="background: #252525;">
                                    <th></th>
                                    <th style="color: white;">Nome</th>
                                    <th style="color: white;">Quantidade</th>
                                    <th style="color: white;">Preço T.</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for linha in carrinho.values %}
                                <tr>
                                    <td class="cart_product_img">
                                        <a href="#"><img src="{% get_media_prefix %}{{ linha.imagem }}"
                                                alt="Product"></a>
                                    </td>
                                    <td class="cart_product_desc">
                                        <h5 style="font-size: 13px; color:white;">
                                            {{ linha.produto_nome }} {{ linha.variacao_nome }}
                                        </h5>
                                    </td>
                                    <td class="price">
                                        <span style="color: white;">
                                            {{ linha.quantidade }}x
                                            {% if linha.preco_unitario_promocional %}
                                            {{ linha.preco_unitario_promocional | formata_preco }}
                                            {% else %}
                                            {{ linha.preco_unitario | formata_preco }}
                                            {% endif %}
                                        </span>
                                    </td>
                                    {% if linha.preco_quantitativo_promocional %}
                                    <td class="price" style="font-size: 15; color:white">
                                        <span>{{ linha.preco_quantitativo_promocional | formata_preco }}</span>
                                        <a class="ml-3"
                                            href="{% url 'produto:removerdocarrinho' %}?vid={{ linha.variacao_id }}">
                                            <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                                        </a>
                                    </td>
                                    {% else %}
                                    <td class="price" style="font-size: 15; font-weight: 100; color: white;">
                                        <span>{{ linha.preco_quantitativo | formata_preco }}</span>
                                        <a class="ml-3"
                                            href="{% url 'produto:removerdocarrinho' %}?vid={{ linha.variacao_id }}">
                                            <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                                        </a>
                                    </td>1
                                    {% endif %}
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-12 col-lg-4">
                    <div id="bordinha" class="cart-summary" style="background: #252525;">
                        <h5 style="color: #fbb710; font-size:25px">Total Carrinho</h5>
                        <ul class="summary-table">
                            <li><span style="color: white;">Qtd Itens:</span> <span style="color: white;">
                                    {{ carrinho | qtd_cart }}x</span>
                            </li>
                            <li><span style="color: white;">total:</span> <span style="color: white;">
                                    {{ carrinho | totals_cart | formata_preco }}</span>
                            </li>
                        </ul>
                        <style>
                            #bordinha {
                                border-width: 8px;
                                border-style: outset;
                                border-color: #fbb710;
                            }
                        </style>
                        <div class="cart-btn mt-100">
                            <a href="cart.html" class="btn amado-btn w-100">Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    {% else %}
    <div class="cart-title mt-50">
        <h2 style="color: #fbb710">Carrinho Vazio</h2>
    </div>
    {% endif %}

    {% include 'parciais/_footer.html' %}
    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>

</body>

</html>

produto/templates/produto/detalhe.html
{% load static %}
{% load eofilters %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'parciais/_head.html' %}
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">
</head>

<body style="background: #252525;">

    {% include 'parciais/_nav.html' %}


    <!-- Product Details Area Start -->
    <div class="single-product-area section-padding-100 clearfix">
        {% include 'parciais/_messages.html' %}

        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-lg-7">
                    <div class="single_product_thumb">
                        <div id="product_details_slider" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li class="active" data-target="#product_details_slider" data-slide-to="0"
                                    style="background-image: url({{ produto.imagem.url }});">
                                </li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <a class="gallery_img" href="img/product-img/pro-big-1.jpg">
                                        <img class="d-block w-100" src="{{ produto.imagem.url }}" alt="First slide">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-5">
                    <div class="single_product_desc">
                        <!-- Product Meta Data -->
                        <div class="product-meta-data">
                            <div class="line"></div>
                            <style>
                                .product-price {
                                    margin-top: 20px;
                                }

                                .produto-price-promocional {
                                    text-decoration: line-through;
                                }
                            </style>
                            <a href="product-details.html">
                                <h6 style="color:#fbb710;">{{ produto.nome }}</h6>
                            </a>
                            <div class="col-lg">
                                <div class="mt-4 mt-lg-0">
                                    <p class="lead">
                                        {% if produto.preco_marketing_promocional %}
                                        <span id="variation-preco" class="lead product-price">
                                            {{ produto.preco_marketing_promocional | formata_preco }}</span>
                                        <span id="variation-preco-promocional"
                                            class="lead product-old-price text-muted">
                                            {{ produto.preco_marketing | formata_preco }}</span>
                                        {% else %}
                                        <span id="variation-preco" class="lead product-price">
                                            {{ produto.preco_marketing | formata_preco }}</span>
                                    </p>
                                    {% endif %}

                                    <!-- Ratings & Review -->
                                    <div class="ratings-review mb-15 d-flex align-items-center justify-content-between">
                                        <div class="ratings" style="color: #fbb710;">
                                            <i id="starss" class="fa fa-star" aria-hidden="true"></i>
                                            <i id="starss" class="fa fa-star" aria-hidden="true"></i>
                                            <i id="starss" class="fa fa-star" aria-hidden="true"></i>
                                            <i id="starss" class="fa fa-star" aria-hidden="true"></i>
                                            <i id="starss" class="fa fa-star" aria-hidden="true"></i>
                                        </div>
                                        <div class="review">
                                            <a href="#">Escreva uma crítica</a>
                                        </div>
                                    </div>
                                    {% for variacao in produto.variacao_set.all %}
                                    {% if variacao.estoque %}
                                    <p class="avaibility"><i class="fa fa-circle"
                                            style="color: rgb(0, 255, 0); height: 8px; margin-top:10px"></i>
                                        Em estoque
                                    </p>
                                    {% else %}
                                    <p class="avaibility"><i class="fa fa-circle"
                                            style="color: grey; height: 8px; margin-top:10px"></i>
                                        Esgotado
                                    </p>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                                    <div class="form-group">
                                        <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                            {% for variacao in produto.variacao_set.all %}
                                            {% if variacao.preco_promocional %}
                                            <option data-preco="{{ variacao.preco_promocional | formata_preco  }}"
                                                data-preco-promocional="{{ variacao.preco | formata_preco }}"
                                                value="{{ variacao.id }}" id="options">{{ variacao }}
                                            </option>
                                            {% else %}
                                            <option data-preco="{{ variacao.preco | formata_preco }}"
                                                value="{{ variacao.id }}" id="options">{{ variacao }}
                                            </option>
                                            {% endif %}
                                            {% endfor %}
                                        </select>
                                        <button type="submit" name="addtocart" value="5" id="dudulindo"
                                            class="btn amado-btn">Adicionar ao Carrinho</button>
                                    </div>
                                    <style>
                                        select {
                                            margin-top: 20px;
                                        }

                                        #starss {
                                            color: #fbb710;
                                            height: 10px;
                                            width: 10px;
                                            margin-top: 10px;
                                        }

                                        #select-variacoes {
                                            font-size: 17px;
                                        }

                                        #options {
                                            font-size: 17px;
                                        }

                                        #dudulindo {
                                            background: #fbb710;
                                            margin-top: 70px;
                                            width: 342px;
                                            height: 80px;
                                            font: bolder;
                                            transition: all 0.5s;

                                        }

                                        a:hover {
                                            text-decoration: none;
                                        }

                                        /* Essence Button */
                                        .amado-btn {
                                            display: inline-block;
                                            min-width: 160px;
                                            height: 55px;
                                            color: #ffffff;
                                            border: none;
                                            border-radius: 0;
                                            padding: 0 7px;
                                            font-size: 18px;
                                            line-height: 56px;
                                            background-color: #fbb710;
                                            font-weight: 400;
                                        }

                                        #dudulindo:hover {
                                            background: black;
                                        }

                                        .amado-btn.active,
                                        .amado-btn:hover,
                                        .amado-btn:focus {
                                            font-size: 18px;
                                            color: #ffffff;
                                            background-color: #131212;
                                        }
                                    </style>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="short_overview my-5">
                <p>{{ produto.descricao_longa }}</p>
            </div>

        </div>
    </div>

    <!-- Product Details Area End -->
    </div>

    {% include 'parciais/_script.html' %}
    {% include 'parciais/_footer.html' %}
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

produto/templates/produto/lista.html
{% extends 'base.html' %}

{% load eofilters %}

{% load static %}

{% block conteudo %}


{% for produto in produtos %}
<div class="single-products-catagory clearfix" style="max-width:100%;">
    <a href="{{ produto.slug }}">
        {% if produto.imagem %}
        <img src="{{ produto.imagem.url }}" alt="{{ produto.nome }}" class="imagenizada">
        {% endif %}
        <div class="hover-content">
            <div class="line"></div>
            {% if produto.preco_marketing_promocional %}
            <p style="font-size: 19px;">{{ produto.preco_marketing_promocional | formata_preco }}</p>
            <p style="text-decoration: line-through; font-size: 13px;">{{ produto.preco_marketing | formata_preco }}</p>
            {% else %}
            <p style="font-size: 19px;">{{ produto.preco_marketing | formata_preco }}</p>
            {% endif %}
            <h4 style="color: white;">{{ produto.nome }}</h4>
        </div>
    </a>
</div>
{% endfor %}
{% endblock %}
{% block pagination %}
<div class="row">
    <div class="col" style="margin-left: 50%;">
        {% include 'parciais/_pagination.html' %}
    </div>
</div>
{% endblock %}